version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - monitoring

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - monitoring

  influxdb:
    image: influxdb:2.7-alpine
    container_name: influxdb
    ports:
      - "8086:8086"
    networks:
      - monitoring
    volumes:
      - influxdb-data:/var/lib/influxdb2
    # C'EST ICI QUE LA MAGIE OPÈRE (Auto-initialisation)
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password12345  # Mot de passe admin (min 8 chars)
      - DOCKER_INFLUXDB_INIT_ORG=monitoring-org
      - DOCKER_INFLUXDB_INIT_BUCKET=monitoring
      # On force le token pour qu'il corresponde à celui de tes applis Java
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=ReqBW1LQswnoYebxpL2p7ZjzudrOUmvdn_Hj5CaZmV1sK48AY0B93nUZQQArB5n1T8YL8Nx_u85MMKZwtFXdhQ==

  producer:
    build:
      context: .
      dockerfile: monitoring-producer/Dockerfile
    container_name: monitoring-producer
    depends_on:
      - kafka
    networks:
      - monitoring
    restart: on-failure

  consumer:
    build:
      context: .
      dockerfile: monitoring-consumer/Dockerfile
    container_name: monitoring-consumer
    depends_on:
      - kafka
      - influxdb
    environment:
      INFLUX_URL: "http://influxdb:8086"
      INFLUX_TOKEN: "ReqBW1LQswnoYebxpL2p7ZjzudrOUmvdn_Hj5CaZmV1sK48AY0B93nUZQQArB5n1T8YL8Nx_u85MMKZwtFXdhQ=="
      INFLUX_ORG: "monitoring-org"
      INFLUX_BUCKET: "monitoring"
    networks:
      - monitoring
    restart: on-failure

  # Ajout de l'API
  api:
    build:
      context: .
      dockerfile: monitoring-api/Dockerfile
    container_name: monitoring-api
    ports:
      - "8080:8080" # On expose le port pour que le prof puisse tester dans son navigateur
    depends_on:
      - influxdb
    environment:
      INFLUX_URL: "http://influxdb:8086"
      INFLUX_TOKEN: "ReqBW1LQswnoYebxpL2p7ZjzudrOUmvdn_Hj5CaZmV1sK48AY0B93nUZQQArB5n1T8YL8Nx_u85MMKZwtFXdhQ=="
      INFLUX_ORG: "monitoring-org"
      INFLUX_BUCKET: "monitoring"
    networks:
      - monitoring
    restart: on-failure

networks:
  monitoring:
    driver: bridge

volumes:
  influxdb-data: